


TABLE_NAME_SNP_ANNOTATION	= "snp_annotation"
TABLE_NAME_REFERENCES		= "snp_references"
TABLE_NAME_TREE				= "tree"
TABLE_NAME_CHROMOSOMES		= "chromosomes"

TABLES = [TABLE_NAME_SNP_ANNOTATION, TABLE_NAME_REFERENCES, TABLE_NAME_TREE, TABLE_NAME_CHROMOSOMES]

COLUMN_PARENT,			COLUMN_PARENT_TYPE			= "parent",			"INTEGER"
COLUMN_GENOTYPE,		COLUMN_GENOTYPE_TYPE		= "name",			"INTEGER"
COLUMN_NODE_ID,			COLUMN_NODE_ID_TYPE			= "node_id",		"TEXT"
COLUMN_POSITION,		COLUMN_POSITION_TYPE		= "position",		"INTEGER"
COLUMN_ANCESTRAL,		COLUMN_ANCESTRAL_TYPE		= "ancestral_base", "VARCHAR(1)"
COLUMN_DERIVED,			COLUMN_DERIVED_TYPE			= "derived_base",	"VARCHAR(1)"
COLUMN_REFERENCE,		COLUMN_REFERENCE_TYPE		= "reference",		"VARCHAR(20)"
COLUMN_DATE,			COLUMN_DATE_TYPE			= "date",			"DATETIME"
COLUMN_CHROMOSOME_ID,	COLUMN_CHROMOSOME_ID_TYPE	= "chromosome_id",	"INTEGER"
COLUMN_CHROMOSOME,		COLUMN_CHROMOSOME_TYPE		= "chromosome",		"VARCHAR(30)"
COLUMN_GENOME_ID,		COLUMN_GENOME_ID_TYPE		= "genome_id",		"INTEGER"
COLUMN_GENOME,			COLUMN_GENOME_TYPE			= "genome",			"VARCHAR(30)"
COLUMN_STRAIN,			COLUMN_STRAIN_TYPE			= "strain",			"VARCHAR(30)"
COLUMN_GENBANK,			COLUMN_GENBANK_TYPE			= "genbank_id",		"VARCHAR(30)"
COLUMN_REFSEQ,			COLUMN_REFSEQ_TYPE			= "refseq_id",		"VARCHAR(30)"
COLUMN_ASSEMBLY,		COLUMN_ASSEMBLY_TYPE		= "assembly_name",	"VARCHAR(30)"


TREE_APPEND = [
    f"PRIMARY KEY {COLUMN_NODE_ID}",
	f"UNIQUE ({COLUMN_PARENT}, {COLUMN_NODE_ID})",
    f"UNIQUE {COLUMN_NODE_ID}",
    f"NOT NULL {COLUMN_PARENT}",
    f"NOT NULL {COLUMN_GENOTYPE}"
]
SNP_APPEND = [
    f"PRIMARY KEY ({COLUMN_CHROMOSOME_ID}, {COLUMN_POSITION}, {COLUMN_NODE_ID})",
	f"FOREIGN KEY ({COLUMN_CHROMOSOME_ID}) REFERENCES {TABLE_NAME_CHROMOSOMES} ({COLUMN_CHROMOSOME_ID})",
    f"FOREIGN KEY ({COLUMN_NODE_ID}) REFERENCES {TABLE_NAME_TREE} ({COLUMN_NODE_ID})",
    f"UNIQUE {COLUMN_POSITION}"
]
CHROMOSOMES_APPEND = [
	f"PRIMARY KEY ({COLUMN_CHROMOSOME_ID}, {COLUMN_GENOME_ID})",
	f"FOREIGN KEY ({COLUMN_GENOME_ID}) REFERENCES {TABLE_NAME_REFERENCES} ({COLUMN_GENOME_ID})",
    f"UNIQUE {COLUMN_CHROMOSOME_ID}",
    f"NOT NULL {COLUMN_CHROMOSOME}",
    f"NOT NULL {COLUMN_GENOME_ID}"
]
REFERENCE_APPEND = [
    f"PRIMARY KEY {COLUMN_GENOME_ID}",
    f"UNIQUE {COLUMN_GENBANK}",
    f"UNIQUE {COLUMN_REFSEQ}",
    f"UNIQUE {COLUMN_ASSEMBLY}"
]
